### ISSUE TITLE
Testnet release no proper tag

### ISSUE THREAD

**Issue by bert2002** [InjectiveLabs/testnet-config#4]
Hi,
it seems the testnet release does not have proper tags for the containers, that makes it very difficult to do proper testing. Is this intended or a bug?

Thanks,
bert

**Comment by bert2002** [comment]
Actually there is no image with that tag either
```
# docker run public.ecr.aws/l9h3g6c6/injective-core:v0.0.0 injectived version
Unable to find image 'public.ecr.aws/l9h3g6c6/injective-core:v0.0.0' locally
docker: Error response from daemon: manifest for public.ecr.aws/l9h3g6c6/injective-core:v0.0.0 not found: manifest unknown: Requested image not found.
```

**Comment by achilleas-kal** [comment]
Hi @bert2002 added the release information here: https://github.com/InjectiveLabs/testnet/releases/tag/v1.12.9-testnet-1703762556
